### ISSUE TITLE
Resource Loading Fails

### ISSUE THREAD

**Issue by Mileter** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#862]
**Expected Behaviour**

void org.mtr.mod.render.RenderSignalBase.<init>(org.mtr.mapping.mapper.BlockEntityRenderer$Argument, boolean, int)' **is supposed to load.**

**Actual Behaviour**
A clear and concise description of what actually happened.

```Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void org.mtr.mod.render.RenderSignalBase.<init>(org.mtr.mapping.mapper.BlockEntityRenderer$Argument, boolean, int)'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void org.mtr.mod.render.RenderSignalBase.<init>(org.mtr.mapping.mapper.BlockEntityRenderer$Argument, boolean, int)'
	at net.londonunderground.mod.render.RenderTunnelSignalLight.<init>(RenderTunnelSignalLight.java:18)
	at net.londonunderground.mod.InitClient.lambda$init$0(InitClient.java:13)
	at org.mtr.mapping.registry.RegistryClient.lambda$registerBlockEntityRenderer$0(RegistryClient.java:45)
	at net.minecraft.class_5616.method_32145(class_5616.java:47)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at net.minecraft.class_5616.method_32146(class_5616.java:45)
	at net.minecraft.class_824.method_14491(class_824.java:125)
	at net.minecraft.class_4013.method_29490(class_4013.java:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	... 12 more
```

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Start the game with logs.
2. In game see "Resource reload fail"
3. See that in log, get the above output.
4. See that all resources are disabled.

**Crash Report**
Attach a crash report to the issue.

There is no crash report. Minecraft caught the error,

**Screenshots**

![圖片](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/assets/90982151/b422e00e-ff8d-46cf-8d91-4fe618b51233)

**Environment**

- Minecraft Version:

1.20.1

- Installed Mods:

fabric-api-0.92.0+1.20.1
modmenu-7.2.2
MTR-fabric-4.0.0-beta-7+1.20.1 (#1619)
MTR-London-Underground-Addon-fabric+.1.20.1

**Additional Information**
Anything else you want to add?

Even though the initial cause was londonunderground, the error seems to be the 
`void org.mtr.mod.render.RenderSignalBase.<init>(org.mtr.mapping.mapper.BlockEntityRenderer$Argument, boolean, int)`
function.

**Comment by Kenny-Hui** [comment]
The addon author have to make an update to stay compatible with the latest MTR Build.

In-development version of MTR is expected to change and can break compatibility with addon mods utilizing the functions of the MTR Mod.

If you cannot afford running without the addon/wait for the author to update, you are highly recommended to stay on the latest published beta version of MTR 4 instead of GitHub Builds.

**Comment by Mileter** [comment]
it was JCM
