### ISSUE TITLE
Can't Use Dashboard On Server

### ISSUE THREAD

**Issue by Leonmmcoset** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#890]
**Expected Behaviour**
I just run a server on 1.19.4 with MTR 4.0.0-beta 8
But I can't use any dashboard on my server.
but if i am in outher dimension，the dashboard can't open.why?

**Reproduction Steps**
Steps to reproduce the behaviour:

1.Open a server
2.Use dashboard

**Crash Report**
（Didn't crash）
java.lang.IllegalStateException: !ASYNC: s=OPEN,api=BLOCKING,sc=true,e=null
	at org.mtr.libraries.org.eclipse.jetty.server.HttpOutput.setWriteListener(HttpOutput.java:1478) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at org.mtr.core.servlet.ServletBase.sendResponse(ServletBase.java:104) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at org.mtr.core.servlet.ServletBase.buildResponseObject(ServletBase.java:160) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at org.mtr.core.servlet.ServletBase.lambda$null$2(ServletBase.java:93) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at org.mtr.core.data.Depot.lambda$null$6(Depot.java:392) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at org.mtr.core.data.Depot.updateGenerationStatus(Depot.java:372) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at org.mtr.core.data.Depot.finishGeneratingPath(Depot.java:201) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at org.mtr.core.data.Siding.finishGeneratingPath(Siding.java:511) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at org.mtr.core.data.Siding.lambda$tick$7(Siding.java:222) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at org.mtr.core.path.SidingPathFinder.findPathTick(SidingPathFinder.java:142) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at org.mtr.core.data.Siding.tick(Siding.java:216) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at java.util.Collection.removeIf(Collection.java:583) ~[?:?]
	at org.mtr.core.simulation.Simulator.tick(Simulator.java:100) ~[MTR-forge-4.0.0-beta-8+1.19.4.jar%23101!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Screenshots**

**Environment**

- Minecraft Version:1.19.4
- Installed Mods:Only MTR

**Additional Information**
Anything else you want to add?

**Comment by jonafanho** [comment]
Can you please send the entire log as well? Thanks.

**Comment by Leonmmcoset** [comment]
Cilent Log:
[latest.log](https://github.com/user-attachments/files/16042680/latest.log)
Server Log:
[latest.log](https://github.com/user-attachments/files/16042694/latest.log)

**Comment by Kenny-Hui** [comment]
Merging into #900
