### ISSUE TITLE
Select station sign crash

### ISSUE THREAD

**Issue by duduskz** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#953]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

When I'm editing a sign, it crashes when I click on a station in Station

### Reproduction Steps

1. Place the railway sign
2. Edit using the brush
3. Enter Station Selection
4. Select the first station, random crash

### In-game Log and Crash Report

[099月2024 17:59:45.712] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering Block Entity
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:170) ~[forge-1.20.4-49.1.4-client.jar:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112267_(BlockEntityRenderDispatcher.java:84) ~[forge-1.20.4-49.1.4-client.jar:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1586) ~[forge-1.20.4-49.1.4-client.jar:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1598) ~[forge-1.20.4-49.1.4-client.jar:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1221) ~[forge-1.20.4-49.1.4-client.jar:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1250) ~[forge-1.20.4-49.1.4-client.jar:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:801) ~[forge-1.20.4-49.1.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:234) ~[forge-1.20.4-49.1.4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.20.4-49.1.4.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.20.4-49.1.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-10.1.2.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74) ~[modlauncher-10.1.2.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:114) ~[modlauncher-10.1.2.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:73) ~[modlauncher-10.1.2.jar:?]
	at cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) ~[modlauncher-10.1.2.jar:?]
	at net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) ~[bootstrap-2.1.0.jar:2.1.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) ~[bootstrap-2.1.0.jar:2.1.0]
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) ~[bootstrap-2.1.0.jar:2.1.0]
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) ~[bootstrap-2.1.0.jar:2.1.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) ~[JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) ~[JavaWrapper.jar:?]
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.mtr.mod.data.IGui.insertTranslation(java.lang.String, java.lang.String, int, java.lang.String[])'
	at org.mtr.mod.render.RenderRailwaySign.md444c71$lambda$drawSign$13$0(RenderRailwaySign.java:703) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177) ~[?:?]
	at java.util.stream.LongPipeline$9$1.accept(LongPipeline.java:375) ~[?:?]
	at java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:183) ~[?:?]
	at org.mtr.libraries.it.unimi.dsi.fastutil.longs.LongSpliterators$SpliteratorFromIterator.forEachRemaining(LongSpliterators.java:1339) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at org.mtr.libraries.it.unimi.dsi.fastutil.longs.LongSpliterator.forEachRemaining(LongSpliterator.java:86) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at org.mtr.mod.render.RenderRailwaySign.drawSign(RenderRailwaySign.java:704) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at org.mtr.mod.render.RenderRailwaySign.render(RenderRailwaySign.java:98) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at org.mtr.mod.render.RenderRailwaySign.render(RenderRailwaySign.java:35) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at org.mtr.mapping.mapper.BlockEntityRenderer.lambda$render$0(BlockEntityRenderer.java:19) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at org.mtr.mapping.mapper.GraphicsHolder.createInstanceSafe(GraphicsHolder.java:50) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at org.mtr.mapping.mapper.GraphicsHolder.createInstanceSafe(GraphicsHolder.java:40) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at org.mtr.mapping.mapper.BlockEntityRenderer.render(BlockEntityRenderer.java:19) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at org.mtr.mapping.mapper.BlockEntityRenderer.m_6922_(BlockEntityRenderer.java:10) ~[[我的世界铁路]%20MTR-forge-4.0.0-beta-9+1.20.4.jar!/:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:116) ~[forge-1.20.4-49.1.4-client.jar:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.lambda$renderTileEntity$0(BlockEntityRenderDispatcher.java:86) ~[forge-1.20.4-49.1.4-client.jar:?]
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112278_(BlockEntityRenderDispatcher.java:163) ~[forge-1.20.4-49.1.4-client.jar:?]
	... 32 more

### Mod Loader

Forge

### Minecraft Version

1.20.4

### Minecraft Transit Railway Version

4.0.0

### Operating System

Windows 11

### List of Mods or Modpack You Were Using

![image](https://github.com/user-attachments/assets/17dcaa8d-8f85-463d-8315-0ae020c6258e)

**Comment by Kenny-Hui** [comment]
Tianjin Metro addon not compatible with MTR beta-9 yet
https://github.com/ZiYueCommentary/Tianjin-Metro/issues/1
