### ISSUE TITLE
not working (ON BEHALF)

### ISSUE THREAD

**Issue by 888845** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#965]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

This error repeated at least once a second.

Server was/is running Debian Linux - Minecraft 1.20.1, Fabric Loader 0.15.11, latest Beta 9 version of MTR - as part of a heavily modified version of the Quantum Freedom 2 modpack (to be clear, the pack was modified, not MTR or any of the mods linked to MTR).

### Reproduction Steps

1.
2.
3.

### In-game Log and Crash Report

Had repeating NullPointerException on my server, behaved similarly to this report. Missing tracks, non-functioning dashboard, etc. Unfortunately I do not have the world file, as it was accidentally wiped due to an operator error (see issue/suggestion https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues/962) but I do have the error stack by way of the server log:

[12:05:29] [Server thread/FATAL]: 
java.lang.NullPointerException: Cannot read field "node" because the return value of "org.mtr.core.tool.Utilities.getElement(java.util.List, int)" is null
	at org.mtr.core.path.SidingPathFinder.padConnectionDetailsList(SidingPathFinder.java:178) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
	at org.mtr.core.path.SidingPathFinder.tick(SidingPathFinder.java:73) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
	at org.mtr.core.path.SidingPathFinder.findPathTick(SidingPathFinder.java:127) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
	at org.mtr.core.data.Siding.tick(Siding.java:212) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
	at java.util.Collection.removeIf(Collection.java:583) ~[?:?]
	at org.mtr.core.simulation.Simulator.tick(Simulator.java:100) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
	at org.mtr.libraries.it.unimi.dsi.fastutil.objects.ObjectImmutableList.forEach(ObjectImmutableList.java:219) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
	at org.mtr.core.Main.manualTick(Main.java:80) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
	at org.mtr.mod.Init.lambda$init$13(Init.java:216) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
	at org.mtr.mapping.registry.EventRegistry.lambda$registerStartServerTick$4(EventRegistry.java:41) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:34) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-15099849194dcb7e.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cha000$fabric-lifecycle-events-v1$onStartTick(MinecraftServer.java:6857) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
This error repeated at least once a second.

Server was/is running Debian Linux - Minecraft 1.20.1, Fabric Loader 0.15.11, latest Beta 9 version of MTR - as part of a heavily modified version of the Quantum Freedom 2 modpack (to be clear, the pack was modified, not MTR or any of the mods linked to MTR).

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Minecraft Transit Railway Version

4.00 beta 9

### Operating System

debian linux

### List of Mods or Modpack You Were Using

idk

### Extra Information

DONE ON BEHALF OF @Kenny-Hui

**Comment by james5922** [comment]
This was my report, btw
