### ISSUE TITLE
Replaces issue #965 - server side NPE during pathfinding

### ISSUE THREAD

**Issue by james5922** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#966]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

Server-side Null Pointer Exception during pathfinding on every second or so (possibly every tick). 
Tracks would disappear and the train dashboard would become unusable for clients.

Unfortunately, I do not have access to the world file anymore due to an operator error (see report/suggestion #962)

### Reproduction Steps

1. (unclear)

Intended train path had multiple stops and was quite long.

### In-game Log and Crash Report

```
[12:05:29] [Server thread/FATAL]:
java.lang.NullPointerException: Cannot read field "node" because the return value of "org.mtr.core.tool.Utilities.getElement(java.util.List, int)" is null
at org.mtr.core.path.SidingPathFinder.padConnectionDetailsList(SidingPathFinder.java:178) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
at org.mtr.core.path.SidingPathFinder.tick(SidingPathFinder.java:73) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
at org.mtr.core.path.SidingPathFinder.findPathTick(SidingPathFinder.java:127) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
at org.mtr.core.data.Siding.tick(Siding.java:212) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
at java.util.Collection.removeIf(Collection.java:583) ~[?:?]
at org.mtr.core.simulation.Simulator.tick(Simulator.java:100) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
at org.mtr.libraries.it.unimi.dsi.fastutil.objects.ObjectImmutableList.forEach(ObjectImmutableList.java:219) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
at org.mtr.core.Main.manualTick(Main.java:80) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
at org.mtr.mod.Init.lambda$init$13(Init.java:216) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
at org.mtr.mapping.registry.EventRegistry.lambda$registerStartServerTick$4(EventRegistry.java:41) ~[MTR-fabric-4.0.0-beta-9+1.20.1.jar:?]
at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:34) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-15099849194dcb7e.jar:?]
at net.minecraft.server.MinecraftServer.handler$cha000$fabric-lifecycle-events-v1$onStartTick(MinecraftServer.java:6857) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
This repeated at least once a second.

I also received something to this effect, repeatedly.
```
[20Sept2024 15:44:54.234] [pool-176-thread-1/FATAL] [TransportSimulationCore/]:
java.lang.NullPointerException: null
[20Sept2024 15:44:54.242] [pool-176-thread-1/FATAL] [TransportSimulationCore/]:
java.lang.NullPointerException: null
[20Sept2024 15:44:54.252] [pool-176-thread-2/FATAL] [TransportSimulationCore/]:
java.lang.NullPointerException: null
[20Sept2024 15:44:54.263] [pool-176-thread-3/FATAL] [TransportSimulationCore/]:
java.lang.NullPointerException: null
[20Sept2024 15:44:54.273] [pool-176-thread-3/FATAL] [TransportSimulationCore/]:
java.lang.NullPointerException: null
[20Sept2024 15:44:54.283] [pool-176-thread-3/FATAL] [TransportSimulationCore/]:
java.lang.NullPointerException: null
[20Sept2024 15:44:54.292] [pool-176-thread-3/FATAL] [TransportSimulationCore/]:
java.lang.NullPointerException: null
```

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Minecraft Transit Railway Version

MTR 4 Beta 9

### Operating System

Linux/Debian

### List of Mods or Modpack You Were Using

Pack was a very heavily modified version of Quantum Freedom 2.

```
[22:45:50] [main/INFO]: Loading 404 mods:
	- ad_astra 1.15.18
	   \-- javazoom_jlayer 1.0.1
	- ad_astra_giselle_addon 6.5
	- advanced_reborn 1.2.8
	- ae2 15.2.12
	   \-- team_reborn_energy 3.0.0
	- ae2wtlib 15.2.1-fabric
	- alloy_forgery 2.1.2+1.20
	- amendments 1.20-1.2.11
	   \-- mixinextras 0.3.6
	- appbot 1.5.0
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- argonauts 1.0.10
	- automobility 0.4.2+1.20.1-fabric
	   \-- jsonem 0.2.1+1.20
	- azurelib 2.0.35
	- bakery 1.1.15
	- balm-fabric 7.3.9
	   \-- kuma_api 20.1.8
	- beachparty 1.1.5
	- beaconoverhaul 1.8.4+1.20
	   \-- reach-entity-attributes 2.4.0
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.4
	- betterendisland 1.20-Fabric-2.0.6
	- betterfortresses 1.20-Fabric-2.0.6
	- betterjungletemples 1.20-Fabric-2.0.5
	- bettermineshafts 1.20-Fabric-4.0.4
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterstrongholds 1.20-Fabric-4.0.3
	- betterwitchhuts 1.20-Fabric-3.0.3
	- bewitchment 1.20-8
	   |-- impersonate 2.10.2
	   |-- playerabilitylib 1.8.0
	   |-- reach-entity-attributes 2.4.0
	   |-- step-height-entity-attribute 1.2.0
	   \-- terraform-wood-api-v1 7.0.3
	- blahaj 0.3.2
	- bookshelf 20.2.13
	- botania 1.20.1-446-FABRIC
	   |-- fiber 0.23.0-2
	   \-- reach-entity-attributes 2.4.0
	- botanypots 13.0.39
	- botarium 2.3.4
	   \-- team_reborn_energy 3.0.0
	- brewery 1.1.9
	- c2me 0.2.0+alpha.11.13
	   |-- c2me-base 0.2.0+alpha.11.13
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.13
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.13
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.13
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.13
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.13
	   |-- c2me-notickvd 0.2.0+alpha.11.13
	   |-- c2me-opts-allocs 0.2.0+alpha.11.13
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.13
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.13
	   |-- c2me-opts-math 0.2.0+alpha.11.13
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.13
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.13
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.13
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.13
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.13
	   |-- c2me-server-utils 0.2.0+alpha.11.13
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.13
	   |-- c2me-threading-lighting 0.2.0+alpha.11.13
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.13
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- mixinextras 0.3.6
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- candlelight 1.2.13
	- capes 1.5.2+1.20
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- cccbridge 1.6.2b-fabric
	- chococraft 0.9.12
	- cinderscapes 4.0.10
	   |-- biolith 1.0.0-beta.1
	   |-- cinderscapes-client 4.0.10
	   |-- cinderscapes-common 4.0.10
	   |-- cinderscapes-worldgen 4.0.10
	   |-- terraform-biome-remapper-api-v1 7.0.3
	   |-- terraform-shapes-api-v1 7.0.3
	   |-- terraform-surfaces-api-v1 7.0.3
	   \-- terraform-wood-api-v1 7.0.3
	- cloth-config 11.1.136
	   \-- cloth-basic-math 0.6.1
	- computercraft 1.113.1
	   |-- cc_tweaked_cobalt 0.9.3
	   |-- com_jcraft_jzlib 1.1.3
	   |-- io_netty_netty-codec-http 4.1.82
	   |-- io_netty_netty-codec-socks 4.1.82
	   \-- io_netty_netty-handler-proxy 4.1.82
	- continuity 3.0.0-beta.5+1.20.1
	- controlling 12.0.2
	- cookingforblockheads 16.0.6
	- coroutil 1.20.1-1.3.7
	- cosmetic-armor 1.6.0
	- craterlib 2.1.0
	- create 0.5.1-f-build.1417+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_obj_loader 2.3.2+1.20.1
	   |-- porting_lib_tags 3.0
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             |-- porting_lib_gametest 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_cooking 1.0.0
	- createdeco 2.0.2-1.20.1-fabric
	- createrailwaysnavigator 1.20.1-0.5.5
	   \-- dragonlib 1.20.1-2.1.14
	- darkutils 17.0.3
	- diagonalfences 8.1.4
	   \-- diagonalblocks 8.0.5
	- diggusmaximus 1.5.9-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- doapi 1.2.15
	- drippyloadingscreen 3.0.2
	- emojiful 4.2.0
	   \-- com_esotericsoftware_yamlbeans_yamlbeans 1.15
	- enhancedworkbenches 1.1.3+1.20.1
	   \-- yet_another_config_lib_v3 3.2.2+1.20
	        |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	        |-- org_quiltmc_parsers_gson 0.2.1
	        \-- org_quiltmc_parsers_json 0.2.1
	- entangled 1.3.19
	- entityculling 1.7.0
	- essential_commands 0.35.3-mc1.20.1
	   |-- ec-core 1.3.0-mc1.20.1
	   |    \-- playerabilitylib 1.8.0
	   \-- playerabilitylib 1.8.0
	- exordium 1.2.1-mc1.20.1
	- expandedstorage 10.3.0-beta.5
	- extended_drawers 2.1.1+mc.1.20.1
	   |-- config_toolkit 1.0.0
	   |    |-- io_determann_shadow-api-17 0.1.1
	   |    \-- net_fabricmc_javapoet 0.1.0
	   |-- graphlib 1.4.0+1.20
	   |    |-- kmodlib-overlay 0.2.12+1.20
	   |    \-- libnetworkstack 0.10.0
	   \-- noindium 1.1.0+1.20
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.12.1+kotlin.2.0.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.1
	- fabricloader 0.15.11
	- fallingtree 4.3.4
	- fancymenu 3.2.3
	   |-- com_github_keksuccino_japng 0.5.3
	   \-- com_github_rtyley_animated-gif-lib-for-java animated-gif-lib-1.7
	- fastquit 3.0.0+1.20+
	- ferritecore 6.0.1
	- fibers 1.3
	- forgeconfigapiport 8.0.0
	- friendsandfoes 2.0.17
	   \-- mixinextras 0.3.6
	- frostiful 1.0.11
	   \-- mm 2.3
	- fusion 1.1.1
	- geckolib 4.4.9
	   \-- com_eliotlash_mclib_mclib 20
	- graveyard 3.0
	- herbalbrews 1.0.8.1
	- immediatelyfast 1.2.21+1.20.4
	   \-- net_lenni0451_reflect 1.3.4
	- immersive_aircraft 1.1.2+1.20.1
	   \-- org_mariuszgromada_math_mathparser_org-mxparser 5.2.1
	- immersive_armors 1.6.1+1.20.1
	- immersive_melodies 0.3.0+1.20.1
	- indium 1.0.34+mc1.20.1
	- inventorysorter 1.9.0-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- iris 1.7.2+mc1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- jade 11.11.0+fabric
	- java 22
	- konkrete 1.8.1
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lazydfu 0.1.3
	- letmedespawn 1.2.1
	- lexiconfig 1.3.11
	- lithium 0.11.2
	- lmft 1.0.2+1.20
	- loadmyresources 1.0.4
	- logicates 1.1.0+1.20
	- lootr 0.7.33.81
	- man_of_many_planes 0.2.0+1.20.1
	- mcpitanlib 2.4.4-1.20.1-fabric
	- meadow 1.3.19
	   \-- mixinsquared 0.1.2-beta.5
	- melody 1.0.3
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- modern_industrialization 1.8.6
	   |-- magna 1.10.1+1.20.1
	   |    \-- omega-config 1.0.8
	   |-- noindium 1.1.0+1.20
	   |-- playerabilitylib 1.8.0
	   \-- team_reborn_energy 3.0.0
	- moderndynamics 0.7.0-beta
	   \-- team_reborn_energy 3.0.0
	- modernfix 5.19.4+mc1.20.1
	- modmenu 7.2.2
	- moonlight 1.20-2.12.21
	   \-- mixinextras 0.3.6
	- moreculling 1.20.4-0.24.0
	   \-- conditional-mixin 0.3.2
	- mousetweaks 2.26
	- msd 1.3.9-e1
	- mtr 4.0.0-beta-9
	- nethervinery 1.2.14
	- nochatreports 1.20.1-v2.2.2
	- noisium 2.3.0+mc1.20-1.20.1
	- opaccreatesupport 1.6.0
	- openpartiesandclaims 0.23.2
	- owo 0.11.2+1.20
	- packetfixer 1.4.2
	- paperdoll 8.0.0
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- pehkui 3.8.3+1.14.4-1.21
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- pfm 1.2.1
	- plushables 1.1.3
	- polymorph 0.49.6+1.20.1
	   \-- spectrelib 0.13.16+1.20.1
	        |-- com_electronwill_night-config_core 3.8.1
	        \-- com_electronwill_night-config_toml 3.8.1
	- powah 5.0.7
	- prometheus 1.2.5
	- puzzleslib 8.1.23
	   \-- puzzlesaccessapi 8.0.7
	- railways 1.6.4+fabric-mc1.20.1
	   \-- mm 2.3
	- reborncore 5.8.7
	   \-- team_reborn_energy 3.0.0
	- rechiseled 1.1.6
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.29
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- roughlyenoughitems 12.1.770
	   \-- error_notifier 1.0.9
	- sandwichable 1.3.1+1.20.1
	   \-- spruceui 5.0.0+1.20
	- searchables 1.0.3
	- servercore 1.5.1+1.20.1
	   |-- fabric-permissions-api-v0 0.3.1
	   |-- org_yaml_snakeyaml 2.2
	   |-- placeholder-api 2.1.3+1.20.1
	   |-- space_arim_dazzleconf_dazzleconf-core 1.3.0-M2
	   \-- space_arim_dazzleconf_dazzleconf-ext-snakeyaml 1.3.0-M2
	- simpleradio 2.4.6.1
	   \-- polymer-registry-sync-manipulator 0.5.19+1.20.1
	- sodium 0.5.11+mc1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   \-- fabric-resource-loader-v0 0.11.10+1802ada577
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sound_physics_remastered 1.20.1-1.4.5
	- spindlemark 1.1.0
	   |-- lib39-core 1.5.0-experimental5+1.20.1
	   \-- lib39-keygen 1.5.0-experimental5+1.20.1
	- starlight 1.1.2+fabric.dbc156f
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.17+a
	- supplementaries 1.20-2.8.17
	   \-- mixinextras 0.3.6
	- tacz 1.0.2-hotfix3
	   |-- com_github_286799714_luaj_luaj-core 3.0.3
	   |-- com_github_286799714_luaj_luaj-jse 3.0.3
	   |-- mkb 1.2.0
	   |-- org_apache_commons_commons-math3 3.6.1
	   |-- porting_lib_core 2.3.4+1.20.1
	   \-- porting_lib_entity 2.3.4+1.20.1
	        \-- porting_lib_mixin_extensions 2.3.4+1.20.1
	- tconstruct 1.20.1-3.6.4.279
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- mantle 1.20.1-1.9.269
	   |    |-- com_google_code_findbugs_jsr305 3.0.2
	   |    \-- star 1.5.2+1.20.1
	   |-- porting_lib_accessors 2.3.4+1.20.1
	   |-- porting_lib_attributes 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_base 2.3.4+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_brewing 2.3.4+1.20.1
	   |-- porting_lib_client_events 2.3.4+1.20.1
	   |-- porting_lib_common 2.3.4+1.20.1
	   |-- porting_lib_config 2.3.4+1.20.1
	   |-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_data 2.3.4+1.20.1
	   |-- porting_lib_entity 2.3.4+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |-- porting_lib_extensions 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_fluids 2.3.4+1.20.1
	   |-- porting_lib_items 2.3.4+1.20.1
	   |-- porting_lib_lazy_registration 2.3.4+1.20.1
	   |-- porting_lib_loot 2.3.4+1.20.1
	   |-- porting_lib_model_loader 2.3.4+1.20.1
	   |-- porting_lib_models 2.3.4+1.20.1
	   |-- porting_lib_networking 2.3.4+1.20.1
	   |-- porting_lib_tool_actions 2.3.4+1.20.1
	   |-- porting_lib_transfer 2.3.4+1.20.1
	   \-- porting_lib_utility 2.3.4+1.20.1
	- techreborn 5.8.7
	   \-- team_reborn_energy 3.0.0
	- terrablender 3.0.1.7
	- terrestria 6.0.13
	   |-- biolith 1.0.0-beta.1
	   |-- terraform-biome-remapper-api-v1 7.0.3
	   |-- terraform-config-api-v1 7.0.3
	   |-- terraform-dirt-api-v1 7.0.3
	   |-- terraform-shapes-api-v1 7.0.3
	   |-- terraform-surfaces-api-v1 7.0.3
	   |-- terraform-tree-api-v1 7.0.3
	   |-- terraform-wood-api-v1 7.0.3
	   |-- terrestria-client 6.0.13
	   |-- terrestria-common 6.0.13
	   \-- terrestria-worldgen 6.0.13
	- the_bumblezone 7.4.18+1.20.1-fabric
	   |-- athena 3.1.1
	   \-- noindium 1.1.0+1.20
	- theprinter 1.4.4+1.20
	- thermoo 2.3.2
	- threadtweak 1.20.2-0.1.1
	- travelersbackpack fabric-1.20.1-9.1.16
	   \-- reach-entity-attributes 2.4.0
	- traverse 7.0.12
	   |-- biolith 1.0.0-beta.1
	   |-- terraform-biome-remapper-api-v1 7.0.3
	   |-- terraform-config-api-v1 7.0.3
	   |-- terraform-surfaces-api-v1 7.0.3
	   |-- terraform-tree-api-v1 7.0.3
	   |-- terraform-wood-api-v1 7.0.3
	   |-- traverse-client 7.0.12
	   |-- traverse-common 7.0.12
	   \-- traverse-worldgen 7.0.12
	- trinkets 3.7.2
	- vinery 1.4.28
	- visualworkbench 8.0.0
	- vmp 0.2.0+beta.7.102
	- voicechat 1.20.1-2.5.22
	- watut 1.20.1-1.1.3
	- waveycapes 1.4.8
	- wilderwild 2.4.6-mc1.20.1
	   |-- frozenlib 1.8-mc1.20.1
	   \-- reach-entity-attributes 2.4.0
	- windchimes 1.2.4+1.20
	- xaerominimap 24.4.0
	- xaeroworldmap 1.39.0
	- yigd 2.0.6
	   \-- libgui 8.1.1+1.20.1
	        |-- jankson 6.0.0+j1.2.3
	        |    \-- blue_endless_jankson 1.2.3
	        \-- libninepatch 1.2.0
	- yungsapi 1.20-Fabric-4.0.5
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsbridges 1.20-Fabric-4.0.3
	- yungsextras 1.20-Fabric-4.0.3
```

**Comment by james5922** [comment]
Note: I am trying to reproduce the bug on the current world - though thus far the NPE has not reoccurred.
