### ISSUE TITLE
Fabric Loader doesn't work right even with the "unsopported" version of MTR.

### ISSUE THREAD

**Issue by Vlakmeister72** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#994]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues?q=is%3Aissue) before.
- [X] This bug still exists in the latest version of the Minecraft Transit Railway mod.
- [X] I have tested this in the official version of Minecraft Transit Railway, not a modified, custom, or unofficial build.

### Describe the Bug

While i tried launching Minecraft with the latest version of MTR and some addon packs and recommended mods on ATLauncher, shortly after the launcher closes, a system crash message says i don't have the supported version, saying i need to pick between 4.0 Beta8 and 4.1 (I have 4.0 Beta11 installed)

### Reproduction Steps

1.Have ATLauncher installed.
2.Install all the mods from my modpacks, latest version. (Athena, Chipped, Dynamic Sound Filters, Fabric API, Fusion, Iris Shaders, JEI, Metropack MTR [Resource pack], MTR 4.0 Beta11, MTR London Underground Addon, MTR Russian Metro addon, MTR Station Decoration addon, Rechiseled, Resourceful lib, Sodium, SuperMartijn642's Core and Config libs.)
3. Launch Minecraft, you should get the message.

### In-game Log and Crash Report

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Minecraft Transit Railway' (mtr) 4.0.0-beta-11 with any version between 4.0.0-beta-8 (inclusive) and 4.1 (exclusive).
More details:
	 - Mod 'MTR Russian Metro Addon' (russianmetro) 4.0.0-2.0.0-beta-2 requires any version between 4.0.0-beta-8 (inclusive) and 4.1 (exclusive) of mod 'Minecraft Transit Railway' (mtr), but only the wrong version is present: 4.0.0-beta-11!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

From the Fabric Loader.

### Mod Loader

Fabric

### Minecraft Version

1.20.4

### Minecraft Transit Railway Version

4.0.0

### Operating System

Windows 10

### List of Mods or Modpack You Were Using

Athena, Chipped, Dynamic Sound Filters, Fabric API, Fusion, Iris Shaders, JEI, Metropack MTR [Resource pack], MTR 4.0 Beta11, MTR London Underground Addon, MTR Russian Metro addon, MTR Station Decoration addon, Rechiseled, Resourceful lib, Sodium, SuperMartijn642's Core and Config libs.

**Comment by Vlakmeister72** [comment]
Problem solved, newer versions on my PC are unstable, hence the crashing. I installed 4.0 Beta9 for my Modpack and the game works perfectly fine.
